# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testapp
  pod 'AppCenter/Crashes', '~> 1.6.0'
  pod 'AppCenter/Analytics', '~> 1.6.0'
  pod 'AppCenterReactNativeShared', '~> 1.5.0'

  

  platform :ios, '9.0'
  target 'testappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'testapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testapp-tvOS

  target 'testapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
